version: "3.8"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: default
      MYSQL_DATABASE: weather

  orm-service:
    restart: always
    build:
      context: ./ORM-service
      dockerfile: Dockerfile
    container_name: orm-service
    volumes:
      - ./ORM-service:/app
    ports:
      - "8001:8001"
    links:
      - mysql
      
  assignment:
    restart: always
    build: ./assignment
    container_name: assignment
    volumes:
      - ./assignment:/app
    ports:
      - "8000:8000"
    links:
      - orm-service
      